[workspace]
workspace.resolver = "2"
members = ["tw-macro", "test-macro"]

# name = "tailwind-rust"
# version = "0.1.0"
# edition = "2021"

[workspace.package]
version = "1.0.0"
edition = "2021"
authors = ["Oyelowo Oyedayo"]
description = "One codebase to rule them all"
documentation = "https://codebreather.com/oyelowo"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


# exclude = ["examples", "tests"]


[workspace.dependencies]
tw-macro = { path = "tw-macro"}

proc-macro2 = "1.0.66"
quote = "1.0.33"
syn = "2.0.29"
